package com.mdotm.petmanager.dto;

import com.mdotm.petmanager.model.Species;
import jakarta.annotation.Nullable;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.Data;

@Data
public class PetDto {
    @Null(message = "ID must not be provided. It is autogenerated.")
    private Long id;
    @NotBlank(message = "Name is required")
    private String name;
    @NotNull(message = "Species is required")
    private Species species;
    @Min(value = 0, message = "Age must be >= 0")
    private Integer age;
    @Nullable
    private String ownerName;
}
